package com.hazelcast.jdbc;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;

import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.assertj.core.api.AssertionsForClassTypes.assertThat;

@ExtendWith(MockitoExtension.class)
public class JdbcConnectionTest {

    @Mock
    private HazelcastSqlClient client;

    @Test
    public void shouldNotSupportAutogeneratedKeys() {
        Connection connection = new JdbcConnection(client);
        assertThatThrownBy(() -> connection.prepareStatement("SELECT * FROM person", new int[]{1, 2, 3}))
                .isInstanceOf(SQLFeatureNotSupportedException.class)
                .hasMessage("Auto-generated keys are not supported.");
    }

    @Test
    void shouldUnwrapConnection() throws SQLException {
        Connection connection = new JdbcConnection(client);
        assertThat(connection.isWrapperFor(JdbcConnection.class)).isTrue();
        assertThat(connection.unwrap(JdbcConnection.class)).isNotNull();
    }
}